MANIFEST.in, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/footer.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/variables.less, invenio_theme_tugraz/config.py, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/header_login.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/login.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/footer.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/frontpage.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/header_frontpage.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/search/invenio_search_ui/header.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/search/invenio_search_ui/search.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/search/search.html, invenio_theme_tugraz/webpack.py, setup.py
Pull request includes new migration to semantic UI, these changes took place for alpha7 release of invenioRDM.
a. webpack.py is rendering ```.less``` stylesheets instead of ```scss```.
b. ```header.html``` is completely modified for TU Graz theme, and is rendered for endpoints such as ```/search``` , ```/deposite``` , ```/communities``` ...
=> Semantic ui

invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/theme.js, invenio_theme_tugraz/templates/invenio_theme_tugraz/footer.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/webpack.py
=> separate html from js

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html
Issue #20 New font was applied
Issue #6 Fixed the highlight effect on hovering the search button
=> Issues #6, #20, #26 fixes

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less
Fixing the font import for the new invenio rdm release; this closes #50
=> Fix the font-family import

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html
Fixing the compatibility issue by adding semantic UI markup and CSS
=> fix the browser compatibility; this closes #40

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/config.py, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
logo svg fill color changed to defaul, also added autofocus to search input. This closes #60
=> added missing css

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
square shape to the elements such as segments, cards, fields, and so on, button ```More``` float to the right of the column. and keeping the input text to the search endpoint. This closes #72.
=> overriden some styles

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/footer.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/frontpage.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/footer.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
=> Footer enhancement

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/login.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/login_user.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/register_user.html
related to #82.
* added the SSO login for TUGRAZ.
* corresponding styles to ```login.less```.
* added a couple of semantic UI classes in order to adjust the form to the center.
* buttons/hyperlink using the standard tugraz theme with hover background color black.
* added the SSO signup for TUGRAZ.
* added two columns, left some texts and right the signup form using semantic-UI classes.
* buttons/hyperlink using the standard tugraz theme with hover background color black.
=> Accounts (WIP)

.github/workflows/pypi-publish.yml, .travis.yml
=> ci:use github actions to publish to pypi

invenio_theme_tugraz/__init__.py, invenio_theme_tugraz/ext.py, setup.py, tests/conftest.py, tests/test_invenio_theme_tugraz.py
The extension class name should always start with uppercase.
=> global: extension class to uppercase.

invenio_theme_tugraz/search.py, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html, invenio_theme_tugraz/views.py
Modified the frontpage template to render the latest data model schema.
This closes #107
=> migrate:upon the changes to the datamodel.

invenio_theme_tugraz/views.py, setup.py, tests/ui/conftest.py, tests/ui/test_views.py
* removing ```# pragma: no cover```
* write tests #95
=> test: removed no cover

invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po, invenio_theme_tugraz/translations/messages.pot
* removed ```Communities``` link
* hard-coded ```Uploads``` link
* adding translation to Uploads
This closes #131
=> feature(ui): refactor submenu

invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
Frontpage:
- change badge color to be the same as on the search page
- change access visualization to be the same as on the search page
=> Feature/various UI bugfixes

invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/register_user.html
=> bugfix: signup page

.github/workflows/tests.yml, setup.py
since we need to install invenio-app-rdm, the dependencies should match.
and the ```tests.yml``` needs services in order to run tests.
=> global: package dependencies

invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/search/components.js, invenio_theme_tugraz/templates/invenio_theme_tugraz/macros/authors.html
access name via creator.person_or_org.name.
partial fix for #153
=> bugfix(*): fix record creators name access

invenio_theme_tugraz/config.py, invenio_theme_tugraz/search.py, invenio_theme_tugraz/templates/invenio_theme_tugraz/comingsoon.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/footer.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html, invenio_theme_tugraz/views.py, setup.py, tests/ui/test_views.py
* disabled search and landingpage override
* search query modified
* routes: injecting routes to override
=> global: required changes for feb release

invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/theme.js, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/frontpage.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/variables.less, invenio_theme_tugraz/config.py, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
=> style: adds styling for zammad form

invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po
=> bugfix: translation order for tug logo

invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/deposit/PublisherField.js, invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/deposit/RDMDepositForm.js
Publisher: makes field required.
Making this field required is needed for DOI minting. to be discussed.
=> PublisherField: makes field required.

invenio_theme_tugraz/search.py
=> bugfix: recent uploads filter only latest version

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/header_login.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/navbar.html
=> bugfix: hyperlink no-decoration

invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/deposit/DoiMint.js, invenio_theme_tugraz/views.py, invenio_theme_tugraz/webpack.py
else: request Error UnicodeEncodeError
=> bugfix: password should b unicode

invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
=> bugfix: created field using old metadata

LICENSE, docs/conf.py, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/register_user.html, invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po, invenio_theme_tugraz/translations/messages.pot, setup.cfg, setup.py
closes #201,
global copyrights.
=> global: copyrights

invenio_theme_tugraz/templates/invenio_theme_tugraz/footer.html
=> footer: adds link to search guide

invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html, invenio_theme_tugraz/views.py
=> ui: display access badge

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/frontpage.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/search.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html
=> ui: adapt color badges

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/variables.less
=> badges(ui): adds tug theme badge colors

invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/macros/authors.html
=> ui: change title to data-tooltip

invenio_theme_tugraz/templates/invenio_theme_tugraz/index.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/landingpage/detail.html, invenio_theme_tugraz/views.py, invenio_theme_tugraz/webpack.py, setup.py
* index/details: resource type uses different field
* func: that will serialize a list of records.
* dep: update/migrate dependencies
=> global: migrate v4

invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/login_user.html, invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po, invenio_theme_tugraz/translations/messages.pot
* adds support for oauth and new configs
This closes #227
=> login_user: extended user login template

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/deposit.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/variables.less
* styling: changes deposit form segment color closes #233 
* css: refactor variables
=> styling: changes deposit form segment color

invenio_theme_tugraz/config.py
=> config: removes i18n config

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less
=> UI divider style

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/login_user.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/accounts/register_user.html, invenio_theme_tugraz/translations/de/LC_MESSAGES/messages.po, invenio_theme_tugraz/translations/messages.pot
fix: remove redundant closing div tag for register
ui: add accordion for better overview
closes #245 
closes #246
=> update register and login view

docs/conf.py, run-tests.sh, setup.py
=> docs: adjust sphinx to flask2

setup.py
=> dep: bump config module

invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/views.py
- align with invenio-app-rdm community changes
- refactor
=> compatibility with v9

setup.cfg
Adapt dependencies for v9
Depends on release of v0.9.0 of  [`invenio-config-tugraz`](https://github.com/tu-graz-library/invenio-config-tugraz)
=> dep: adapt to v9

.github/workflows/pypi-publish.yml
see https://github.com/inveniosoftware/invenio-app-rdm/issues/1675
quick fix until the issue is fully addressed
=> fix: restrict babel version

invenio_theme_tugraz/views.py
closes #268 
Adopt to renaming in view function to match the refactor of serializer
=> fix: adopt to renaming of serialize function

invenio_theme_tugraz/assets/semantic-ui/js/invenio_theme_tugraz/theme.js, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/communities.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/theme.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html, invenio_theme_tugraz/templates/invenio_theme_tugraz/navbar.html
- migrate js to use prettier
- remove grey color of community block and reduce size
- change searchbar layout and use invenio-app-rdm searchbar
- add marc21 and lom to the searchbar
- fix warning from semantic-ui-react Search component
- remove unnecessary html code for header-search-bar
=> update search bar

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/header.less, invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/variables.less
Adapt button color to match our theme.
Without focus:
With focus:
=> css: adapt skip-to-main button

invenio_theme_tugraz/templates/invenio_theme_tugraz/recent_uploads.html
* it is true that types will always exists, but it could be an empty
=> fix: types could be empty list

invenio_theme_tugraz/assets/semantic-ui/less/invenio_theme_tugraz/overrides.less, invenio_theme_tugraz/templates/invenio_theme_tugraz/header.html
=> ui: add banner to header

invenio_theme_tugraz/config.py, invenio_theme_tugraz/templates/invenio_theme_tugraz/default_error.html, invenio_theme_tugraz/views.py
=> add default-page for unhandled errors
